FROM docker.io/library/debian:trixie-slim

# Set working directory
WORKDIR /home/user/eclipse-workspace

# Install dependencies for adding repositories
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Eclipse IDE and Pleiades plugin
ENV ECLIPSE_URL="https://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/2026-03/R/eclipse-jee-2026-03-R-linux-gtk-x86_64.tar.gz"
ENV PLEIADES_URL="https://ftp.jaist.ac.jp/pub/mergedoc/pleiades/build/stable/pleiades.zip"
RUN curl -fsSL -o /tmp/eclipse.tar.gz ${ECLIPSE_URL} \
    && curl -fsSL -o /tmp/pleiades.zip ${PLEIADES_URL}

# Add Eclipse Temurin repository
RUN curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /etc/apt/trusted.gpg.d/adoptium.gpg \
    && echo "deb https://packages.adoptium.net/artifactory/deb $(. /etc/os-release && echo $VERSION_CODENAME) main" | tee /etc/apt/sources.list.d/adoptium.list

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    fonts-noto-cjk \
    git \
    libgtk-3-0 \
    locales \
    temurin-21-jdk \
    unzip \
    xdg-utils \
    zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# User configuration
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} user \
    && useradd -m -u ${UID} -g ${GID} user \
    && chown -R user:user /home/user

# Locale configuration
ENV LANG=ja_JP.UTF-8
RUN sed -i "s/# ${LANG} UTF-8/${LANG} UTF-8/" /etc/locale.gen \
    && locale-gen

# GTK configuration
COPY gtk-3.0/settings.ini /home/user/.config/gtk-3.0/

# Font configuration
COPY fontconfig/fonts.conf /home/user/.config/fontconfig/

# Add Eclipse IDE to PATH
ENV PATH="${PATH}:/opt/eclipse"

# Run Eclipse IDE
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT [ "docker-entrypoint.sh" ]

USER user

CMD [ "eclipse" ]
